INSERT INTO TB_ACCOUNT (ACCOUNT_NO, ACCOUNT_NM) VALUES (1, 'JOHN');
INSERT INTO TB_ACCOUNT (ACCOUNT_NO, ACCOUNT_NM) VALUES (2, 'MAX');

INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0001', '가입축하쿠폰', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0002', '가입축하쿠폰', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0003', '가입축하쿠폰', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0004', '가입축하쿠폰', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0005', '가입축하쿠폰', 2000);