INSERT INTO TB_ACCOUNT (ACCOUNT_NO, ACCOUNT_NM) VALUES (1, 'JOHN');
INSERT INTO TB_ACCOUNT (ACCOUNT_NO, ACCOUNT_NM) VALUES (2, 'MAX');

INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0001', '선착순쿠폰1', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0002', '선착순쿠폰2', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0003', '선착순쿠폰3', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0004', '선착순쿠폰4', 2000);
INSERT INTO TB_COUPON (COUPON_ID, COUPON_NM, COUPON_AMT) VALUES ('C0005', '선착순쿠폰5', 2000);